### ISSUE TITLE
Error with downloads

### ISSUE THREAD

**Issue by Sharzzz001** [Shubhamrawat5/spotify-playlist-downloader#4]
====== GETTING SPOTIFY PLAYLIST INFO ======

getting playlist name
There is a issue with html of webapge. Most probably page didn't load or spotify has changed their html css classes name

getting username
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read property **'innerText'** of undefined
    at __puppeteer_evaluation_script__:4:6
    at ExecutionContext._evaluateInternal (C:\Sharan\spotdl\spotify-playlist-downloader-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Sharan\spotdl\spotify-playlist-downloader-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)    at async getPlaylistList (C:\Sharan\spotdl\spotify-playlist-downloader-main\spotify.js:36:19)
    at async getPlaylistInfo (C:\Sharan\spotdl\spotify-playlist-downloader-main\spotify.js:104:3)
    at async Object.module.exports.getPlaylist (C:\Sharan\spotdl\spotify-playlist-downloader-main\spotify.js:122:3)

**Comment by Shubhamrawat5** [comment]
Fixed. It should be working now
